apiVersion: v1
data:
{{- include "helm-template.secretdata" . | indent 2 }}
{{/* include "render-value" ( dict "value" .Values.secretdata "context" .) | indent 2 */}}
kind: Secret

metadata:
  name: {{ include "helm-template.name" . }}-secrets
  namespace: {{ include "helm-template.namespace" . }}
type: Opaque