{{- range $containers := .Values.containers }}
{{- range $service := $containers.ports }}
{{- if  $service.service_enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-template.name" $ }}-{{ $service.name }}
  namespace: {{ include "helm-template.namespace" $ }}
  labels:
    {{- include "helm-template.selectorLabels" $ | nindent 4 }}
spec:
  type: {{ $service.service_type | default "ClusterIP" }}
  ports:
    - port: {{ $service.service_port | default "8080" }}
      targetPort: {{ $service.port | default "8080" }}
      protocol: TCP
  selector:
    {{- include "helm-template.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}